### ISSUE TITLE
SyntaxError: Unexpected token { in devices.js

### ISSUE THREAD

**Issue by psujit** [thingsSDK/thingssdk-cli#40]
Hello, 

I flashed my microcontroller with Flasher.js and then installed the thingssdk-cli. But after doing so, when I tried to create a new project using: thingssdk new project, it gave me the following error:

/usr/local/lib/node_modules/thingssdk-cli/lib/commands/devices.js:3
const {createDevicesJSON} = require('../devices');
         ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at Object.require (internal/module.js:16:19)
    at /usr/local/lib/node_modules/thingssdk-cli/node_modules/require-directory/index.js:76:17
    at Array.forEach (native)
    at requireDirectory (/usr/local/lib/node_modules/thingssdk-cli/node_modules/require-directory/index.js:59:24)

My node version: v5.5.0(if I upgrade it to 6.0.0 or above, it gives me an error that serialport is compiled with version 46 and 6.0.0 is needs version 48)
My npm version: 3.3.12(tried updating to 4.1.1, but issue persists)

Please let me know what the issue is or where I am going wrong.

Thanks and regards,
Sujit

**Comment by chalkers** [comment]
Once you've upgraded your node to version 6 you need to remove `serialport` and reinstall it. Let me know how it goes.

**Comment by psujit** [comment]
Didn't help. This is the error I am getting

/usr/local/lib/node_modules/thingssdk-cli/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at bindings (/usr/local/lib/node_modules/thingssdk-cli/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/thingssdk-cli/node_modules/serialport/lib/bindings.js:3:35)
    at Module._compile (module.js:541:32)

**Comment by psujit** [comment]
Got it! It is solved now.. Deleted serialport completely and reinstalled it. 
Could not uninstall serialport using npm but deleted it from command line.
